"""update team_member

Revision ID: 69688aabee86
Revises: 1e9f0fe4f1b3
Create Date: 2024-05-16 16:47:46.640942

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69688aabee86'
down_revision: Union[str, None] = '1e9f0fe4f1b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('team_members', sa.Column('team_id', sa.UUID(), nullable=True))
    op.drop_constraint('team_members_group_id_fkey', 'team_members', type_='foreignkey')
    op.create_foreign_key(None, 'team_members', 'teams', ['team_id'], ['id'])
    op.drop_column('team_members', 'group_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('team_members', sa.Column('group_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'team_members', type_='foreignkey')
    op.create_foreign_key('team_members_group_id_fkey', 'team_members', 'teams', ['group_id'], ['id'])
    op.drop_column('team_members', 'team_id')
    # ### end Alembic commands ###
