"""update relationship task table

Revision ID: 9a9f75d33327
Revises: 7a24493f6430
Create Date: 2024-05-21 14:33:43.093246

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a9f75d33327'
down_revision: Union[str, None] = '7a24493f6430'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint('tasks_name_key', 'tasks', type_='unique')
    op.drop_constraint('tasks_status_key', 'tasks', type_='unique')
    op.drop_constraint('tasks_team_id_key', 'tasks', type_='unique')
    op.drop_constraint('tasks_user_id_key', 'tasks', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('tasks_user_id_key', 'tasks', ['user_id'])
    op.create_unique_constraint('tasks_team_id_key', 'tasks', ['team_id'])
    op.create_unique_constraint('tasks_status_key', 'tasks', ['status'])
    op.create_unique_constraint('tasks_name_key', 'tasks', ['name'])
    op.alter_column('tasks', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
