"""Fix account table

Revision ID: f6fa27bb6677
Revises: 4a52812895fb
Create Date: 2024-05-16 23:02:55.006896

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6fa27bb6677'
down_revision: Union[str, None] = '4a52812895fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('email', sa.String(), nullable=False))
    op.add_column('accounts', sa.Column('password', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'accounts', ['email'])
    op.drop_column('accounts', 'account_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('account_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'accounts', type_='unique')
    op.drop_column('accounts', 'password')
    op.drop_column('accounts', 'email')
    # ### end Alembic commands ###
